# Generated by Django 3.0.6 on 2020-05-14 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200513_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
